project_identifier_env: CROWDIN_DOCUSAURUS_PROJECT_ID
api_key_env: CROWDIN_DOCUSAURUS_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  - source: "/website/i18n/en/**/*.json"
    translation: "/website/i18n/%locale%/**/%original_file_name%"
    content_segmentation: 0
  - source: "/docs/*.md"
    translation: "/website/i18n/%locale%/docusaurus-plugin-content-docs/current/%original_file_name%"
    content_segmentation: 0
