module.exports = {
  docs: [
    {
      type: "category",
      label: "Kusama",
      items: [
        "general/kusama/kusama-index",
        {
          type: "category",
          label: "Get Started",
          items: [
            "general/kusama/kusama-getting-started",
            "general/kusama/kusama-faucet",
            "general/kusama/kusama-claims",
            "general/kusama/kusama-endpoints",
            "learn/mirror-learn-balance-transfers",
            "general/mirror-thousand-validators",
            "learn/mirror-learn-auction",
            "learn/mirror-learn-parachains",
            "learn/mirror-learn-parathreads",
            "learn/mirror-learn-crowdloans",
          ],
        },
        {
          type: "category",
          label: "What to Try",
          items: [
            "maintain/kusama/mirror-maintain-guides-how-to-validate-kusama",
            "maintain/mirror-maintain-guides-how-to-stop-validating",
            "maintain/kusama/mirror-maintain-guides-how-to-nominate-kusama",
            "learn/mirror-learn-governance",
            "learn/mirror-learn-identity",
            "learn/mirror-learn-treasury",
            "learn/mirror-learn-registrar",
            "build/mirror-build-build-with-polkadot",
            "build/mirror-build-parachains-rococo",
            "maintain/kusama/maintain-guides-society-kusama",
            "general/kusama/kusama-social-recovery",
          ],
        },
        {
          type: "category",
          label: "What to Break",
          items: ["maintain/mirror-maintain-errors", "general/kusama/kusama-bug-bounty", "general/kusama/kusama-adversarial-cheatsheet"],
        },
        "general/mirror-ens",
        "general/kusama/kusama-ledger",
        "general/kusama/kusama-statemine-ledger",
        "general/kusama/kusama-timeline",
        "general/kusama/kusama-community",
        "general/kusama/kusama-parameters",
        "general/kusama/kusama-coc",
      ],
    },
  ],
};
