extends: existence
message: "Don't use exclamation points in text."
link: "https://developers.google.com/style/exclamation-points"
nonword: true
level: warning
tokens:
  - '\w+!(?:\s|$)'
exceptions:
  - ink!
