extends: substitution
message: "Use '%s' instead of '%s'."
link: "https://developers.google.com/style/word-list"
level: warning
ignorecase: false
action:
  name: replace
swap:
  "(?:e-mail|Email|E-mail)": email
  "(?:file ?path|path ?name)": path
  "(?:kill|terminate|abort)": stop|exit|cancel|end
  "(?:ok|Okay)": OK|okay
  "(?:WiFi|wifi)": Wi-Fi
  '3\-D': 3D
  "un(?:check|select)": clear
  admin: administrator|`admin`
  Ajax: AJAX
  a\.k\.a|aka: or|also known as
  approx\.: approximately
  args: arguments|`args`
  check box: checkbox
  config: configuration|`config`
  disabled?: turn off|off|deactivate
  file name: filename
  HTTPs: HTTPS
  in order to: to
  Nginx: nginx|NGINX
  open-source: open source
  OpenGov: Polkadot OpenGov
  "(?:Polkadot JS|Polkadot.Js|Polkadot.JS)": Polkadot.js
  "(?:PolkadotSDK|Polkadot-SDK|Polkadot sdk)": Polkadot SDK
  "(?:repo|repos)": repository|repositories
  rpc: RPC
  stylesheet: style sheet
  tablename: table name
  url: URL
  vs\.: versus
  whitelist: allowlist 
  "(?:wasm|WASM|WebAssembly)": Wasm
  
  