name: Check Substrate Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-release:
    name: checks Substrate release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check latest substrate links
        run: yarn; node --experimental-json-modules scripts/update-substrate-links.mjs
