name: Check Substrate Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-release:
    name: checks Substrate release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          node-version: '14.x'
      - name: Check latest substrate links
        run: yarn; node scripts/update-substrate.js; node scripts/check-substrate-release.js
