name: Deploy Kusama

# Triggered on commits to the main branch.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Clone and run the site
        run: |
          sudo apt-get install netcat
          yarn
          yarn kusama:start &
          while ! nc -z localhost 3000; do
              sleep 1
              echo waiting for website up...
          done
          yarn kusama:pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: kusama-wiki
          path: kusama-guide/static/kusama-wiki.pdf

      - name: Build
        run: yarn; yarn kusama:build
        env:
          BUILDING: true

      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.1.4
        with:
          path: ./kusama-guide/build
          timeout: 120000