name: Check Markdown links

on: push

jobs:
  mkdocs-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: byrnereese/github-action-mkdocs-link-check@1.0
      with:
         folder-path: 'docs/'