name: Check docs for stale pages (those that have not been updated in more than 21 days) and stale issues (60 days of no activity)

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  # job 1: check for inactive issues and mark as stale - close if still no activity
  close-issues:
    name: check for stale issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 15
          stale-issue-label: "stale issue"
          stale-issue-message: "This issue has been marked stale because it has been open for 60 days with no activity."
          close-issue-message: "This issue has been closed because of being inactive for 15 days since being stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  # job 2: check for inactive issues and mark as stale - close if still no activity        
  check-stale:
    name: Checks for stale files
    runs-on: ubuntu-latest
    env: 
      REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find Docs
        id:   find
        uses: w3f/action-find-old-files@master
      - uses: actions/upload-artifact@v2
        with:
          name: Stale docs
          path: ${{ steps.find.outputs.files }}
      - uses: w3f/action-create-issues-for-old-files@master
        name: Check if Stale Issue Exists
        id: check_if_issue_exists
        with:
          REPO: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          title: STALE
          labels: stale
      - name: Create Issues
        if: steps.check_if_issue_exists.outputs.exists == 'false'
      - uses: w3f/action-create-issues-for-old-files@master
        with:
          randAssignees: '["jakehemmerle", "dannys03", "emresurmeli"]'
          files: ${{ steps.find.outputs.files }}

