name: Check docs for stale pages (those that have not been updated in more than 21 days)

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  check-stale:
    name: Checks for stale files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check for stale files.
        run: yarn; pwd; node scripts/stalecheck.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
